name: CI
on:
  pull_request:
    branches: ['**']
  push:
    branches: ['**']
    tags: [v*]
jobs:
  build:
    name: Build and Test
    strategy:
      matrix:
        os: [ubuntu-latest]
        java: [adopt@1.8]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: coursier/cache-action@v6
      - uses: olafurpg/setup-scala@v13
        with:
          java-version: ${{ matrix.java }}
      - name: Build project
        run: sbt compile
      - name: Start Cassandra
        run: docker-compose -f docker-compose.yml up -d cassandra
      - name: Run tests
        run: sbt test
